import { LoadingProvider } from "@/components/Providers/Loading";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <LoadingProvider>
        <body
          className={cn(
            inter.className,
            "overflow-y-scroll overflow-x-hidden bg-[#030014]"
          )}
        >
          {children}
        </body>
      </LoadingProvider>
    </html>
  );
}
